## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
## CROSS-SHELL PROMPT
## The minimal, blazing-fast, and infinitely customizable prompt for any shell!

format = """
$hostname\
$directory\

$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$hg_branch\
$docker_context\
$package\
$custom\

$sudo\

$fill\
$git_branch\
$git_status\
$git_commit\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$line_break\
$character"""

add_newline = true

[hostname]
ssh_only = true
format = "[](fg:#303446 bg:none)[█](fg:#CAD3F5 bg:#303446)[$ssh_symbol$hostname](bold bg:#CAD3F5)[](fg:#CAD3F5 bg:none) "
disabled = false

[directory]
format = "[](fg:#303446 bg:none)[$path]($style)[█](fg:#303446 bg:none)[](fg:#8AADF4 bg:#303446)[ ](fg:#303446 bg:#8AADF4)[](fg:#8AADF4 bg:none)"
style = "fg:#CAD3F5 bg:#303446 bold"
truncation_length = 3
truncate_to_repo=false
read_only = " "

[character]
success_symbol = "[ ](green bold)"
error_symbol = "[ ](red bold)"

[line_break]
disabled = false

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
min_time = 1
format = "[](fg:#303446 bg:none)[$duration]($style)[](fg:#303446 bg:#303446)[](fg:#C6A0F6 bg:#303446)[󱑂 ](fg:#303446 bg:#C6A0F6)[](fg:#C6A0F6 bg:none)"
disabled = false
style = "fg:#CAD3F5 bg:#303446 bold"

[git_branch]
format = "[](fg:#303446 bg:none)[$branch]($style)[](fg:#303446 bg:#303446)[](fg:#A6DA95 bg:#303446)[](fg:#303446 bg:#A6DA95)[](fg:#A6DA95 bg:none) "
style = "fg:#CAD3F5 bg:#303446"
symbol = " "

[git_status]
format="[](fg:#303446 bg:none)[$all_status$ahead_behind]($style)[](fg:#303446 bg:#303446)[](fg:#8AADF4 bg:#303446)[ ](fg:#303446 bg:#8AADF4)[](fg:#8AADF4 bg:none) "
style = "fg:#CAD3F5 bg:#303446"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = " 󰄸 "
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = " ${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[aws]
symbol = "  "

[conda]
symbol = " "

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[nix_shell]
symbol = " "

[shlvl]
symbol = " "

# Language configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true
